#!/bin/sh

### BEGIN INIT INFO
# Provides:       php5-fcgi
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: PHP5 FastCgi Spawned processes
### END INIT INFO

case "$1" in
  start)
    /var/www/domocan/bin/server_udp > /var/log/domocan.log    
  ;;
  stop)
    pkill server_udp
  ;;
  restart|reload)
    stop
    start
  ;;
  *)
    echo "Usage: domocan {start|stop|restart}"
    exit 1
  ;;
esac
exit $RETVAL

